  name: native-image
  on: [push, pull_request]
  jobs:
    build-binary-unix:
      runs-on: ${{ matrix.os }}
      env:
        GRAALVM_VERSION: 22.0.0.2
        GRAALVM_JAVA: java17
      strategy:
        fail-fast: true
        matrix:
          os: [macos-latest, ubuntu-latest]
          include:
            - os: macos-latest
              label: 'darwin'
            - os: ubuntu-latest
              label: 'linux'
      steps:
      - uses: actions/checkout@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
            !~/.m2/repository/org/eclipse/lemminx
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache GraalVM
        uses: actions/cache@v2
        with:
          path: |
            /opt/hostedtoolcache/GraalVM
            ~/hostedtoolcache/GraalVM
          key: ${{ runner.os }}-graalvm-${{env.GRAALVM_VERSION}}
          restore-keys: |
            ${{ runner.os }}-graalvm-
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: ${{env.GRAALVM_VERSION}}
          java: ${{env.GRAALVM_JAVA}}
      - run: ./mvnw -B package -Dnative -DskipTests $([ $(uname -s) = Linux ] && echo "-Dgraalvm.static=-H:+StaticExecutableWithDynamicLibC") -Dcbi.jarsigner.skip=true
      - run: rm org.eclipse.lemminx/target/*.build_artifacts.txt
      - run: mv org.eclipse.lemminx/target/lemminx-* lemminx-$(git rev-parse --short "$GITHUB_SHA")-${{ matrix.label }}
      - uses: actions/upload-artifact@v2
        with:
          name: lemminx-${{ matrix.label }}
          path: lemminx-*-${{ matrix.label }}
          if-no-files-found: error
    build-binary-windows:
      runs-on: windows-latest
      env:
        GRAALVM_VERSION: 22.0.0.2
        GRAALVM_JAVA: java17
      steps:
      - uses: actions/checkout@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
            !~/.m2/repository/org/eclipse/lemminx
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache GraalVM
        uses: actions/cache@v2
        with:
          path: |
            C:\hostedtoolcache\windows\GraalVM
          key: ${{ runner.os }}-graalvm-${{env.GRAALVM_VERSION}}
          restore-keys: |
            ${{ runner.os }}-graalvm-
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: ${{env.GRAALVM_VERSION}}
          java: ${{env.GRAALVM_JAVA}}
      - run: .\mvnw.cmd -B package -Dnative -DskipTests -D "cbi.jarsigner.skip=true"
      - run: mv org.eclipse.lemminx\target\lemminx-*.exe lemminx-$(git rev-parse --short "$Env:GITHUB_SHA")-win32.exe
      - uses: actions/upload-artifact@v2
        with:
          name: lemminx-win32
          path: lemminx-*-win32.exe
          if-no-files-found: error
